name: Test workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Hello
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

      - name: Checking env variables
        run: |
          echo "workspace is $GITHUB_WORKSPACE"
          echo "VARIABLE=test_${GITHUB_SHA}" >> $GITHUB_ENV
      
      - name: Checking variable
        run: |
          echo "This is the value of VARIABLE: ${{env.VARIABLE}}"
          echo "This is the value of VARIABLE: $VARIABLE"

      - name: Checking initializing variable with shell command
        run: echo "WORKSPACE_FOLDER=$(basename $GITHUB_WORKSPACE)" >> $GITHUB_ENV
      
      - name: Show variable
        run: echo "This is the folder = $WORKSPACE_FOLDER"

      - name: AWS credentials
        run: |
          mkdir -p .aws && echo "[default]" > .aws/credentials
          echo "regin = us-east-1" >> .aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> .aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .aws/credentials
          more .aws/credentials