name: Test workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Hello
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

      - name: Checking env variables
        run: |
        echo "workspace is $GITHUB_WORKSPACE"
        echo "workspace is ${{ github.workspace }}"
